# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://campervan.games
title: Campervan Games
email: campervangames@gmail.com
author: Matthew Deline
description: > # "Write an awesome description for your new site here.
  Campervan Games is a Melbourne based Independent Game Studio focused on creating wholesome, engaging experiences.
copyright: 'Copyright &copy; 2019 Campervan Games. All Rights Reserved.'
credits: '<p>Credits: </p><p>Images by lbbuycom on <a href="https://www.kissclipart.com">kissclipart</a>.</p><p>Hosted on Github Pages using a free to use, open source Bootstrap theme called "Landing Page," created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.</p>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/CampervanGames
  - title: facebook
    url: https://www.facebook.com/CampervanGames/
  - title: itch.io
    url: https://campervangames.itch.io
